In [4]:
!pip install compiam

Collecting compiam
  Downloading compiam-0.4.1-py3-none-any.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.3/48.3 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: attrs>=23.1.0 in /usr/local/lib/python3.12/dist-packages (from compiam) (25.4.0)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from compiam) (3.10.0)
Collecting numpy<=1.26.4,>=1.20.3 (from compiam)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from compiam) (1.5.3)
Collecting pathlib~=1.0.1 (from compiam)
  Downloading pathlib-1.0.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: tqdm>=4.66.1 in /usr/local/lib/python3.12/dist-packages (from compiam) (4.67.3)
Requirement already satisfied: IPython>=7.34.0 in /usr/local/lib/python3.12/dist-packages (from compiam) (7.34.0)
Requirement already satisfied: ipywidgets<8,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from compiam) (7.7.1)
Requirement already satisfied: Jinja2~=3.1.2 in /usr/local/lib/python3.12/dist-packages (from compiam) (3.1.6)
Collecting configobj~=5.0.6 (from compiam)
  Downloading configobj-5.0.9-py2.py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from compiam) (0.13.2)
Requirement already satisfied: librosa>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from compiam) (0.11.0)
Requirement already satisfied: soundfile>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from compiam) (0.13.1)
Collecting scikit-learn~=1.5.2 (from compiam)
  Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting scikit-image~=0.24.0 (from compiam)
  Downloading scikit_image-0.24.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Collecting opencv-python~=4.6.0 (from compiam)
  Downloading opencv_python-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting hmmlearn==0.3.3 (from compiam)
  Downloading hmmlearn-0.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting fastdtw~=0.3.4 (from compiam)
  Downloading fastdtw-0.3.4.tar.gz (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 9.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting compmusic==0.4 (from compiam)
  Downloading compmusic-0.4-py3-none-any.whl.metadata (2.5 kB)
Collecting mirdata==0.3.9 (from compiam)
  Downloading mirdata-0.3.9-py3-none-any.whl.metadata (9.1 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from compmusic==0.4->compiam) (2.32.4)
Requirement already satisfied: scipy>=0.19 in /usr/local/lib/python3.12/dist-packages (from hmmlearn==0.3.3->compiam) (1.16.3)
Requirement already satisfied: chardet>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mirdata==0.3.9->compiam) (5.2.0)
Collecting Deprecated>=1.2.14 (from mirdata==0.3.9->compiam)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: h5py>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mirdata==0.3.9->compiam) (3.15.1)
Collecting jams>=0.3.4 (from mirdata==0.3.9->compiam)
  Downloading jams-0.3.5-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: pandas>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from mirdata==0.3.9->compiam) (2.2.2)
Collecting pretty-midi>=0.2.10 (from mirdata==0.3.9->compiam)
  Downloading pretty_midi-0.2.11.tar.gz (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 83.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyyaml>=6.0 in /usr/local/lib/python3.12/dist-packages (from mirdata==0.3.9->compiam) (6.0.3)
Requirement already satisfied: openpyxl>=3.0.10 in /usr/local/lib/python3.12/dist-packages (from mirdata==0.3.9->compiam) (3.1.5)
Requirement already satisfied: smart-open>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from smart-open[all]>=5.0.0->mirdata==0.3.9->compiam) (7.5.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from IPython>=7.34.0->compiam) (75.2.0)
Collecting jedi>=0.16 (from IPython>=7.34.0->compiam)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from IPython>=7.34.0->compiam) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from IPython>=7.34.0->compiam) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from IPython>=7.34.0->compiam) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from IPython>=7.34.0->compiam) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from IPython>=7.34.0->compiam) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from IPython>=7.34.0->compiam) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from IPython>=7.34.0->compiam) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from IPython>=7.34.0->compiam) (4.9.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets<8,>=7.0.0->compiam) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets<8,>=7.0.0->compiam) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets<8,>=7.0.0->compiam) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets<8,>=7.0.0->compiam) (3.0.16)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2~=3.1.2->compiam) (3.0.3)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->compiam) (3.1.0)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->compiam) (0.60.0)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->compiam) (1.9.0)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->compiam) (1.0.0)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->compiam) (4.15.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->compiam) (0.4)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.10.1->compiam) (1.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->compiam) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->compiam) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->compiam) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->compiam) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->compiam) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->compiam) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->compiam) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->compiam) (2.9.0.post0)
Requirement already satisfied: networkx>=2.8 in /usr/local/lib/python3.12/dist-packages (from scikit-image~=0.24.0->compiam) (3.6.1)
Requirement already satisfied: imageio>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image~=0.24.0->compiam) (2.37.2)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image~=0.24.0->compiam) (2026.2.20)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn~=1.5.2->compiam) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from soundfile>=0.12.1->compiam) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->soundfile>=0.12.1->compiam) (3.0)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from Deprecated>=1.2.14->mirdata==0.3.9->compiam) (2.1.1)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->compiam) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->compiam) (7.4.9)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->compiam) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->compiam) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->compiam) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->compiam) (6.5.1)
Requirement already satisfied: jsonschema>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from jams>=0.3.4->mirdata==0.3.9->compiam) (4.26.0)
Collecting mir_eval>=0.8.2 (from jams>=0.3.4->mirdata==0.3.9->compiam)
  Downloading mir_eval-0.8.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sortedcontainers>=2.1.0 (from jams>=0.3.4->mirdata==0.3.9->compiam)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from jams>=0.3.4->mirdata==0.3.9->compiam) (1.17.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->IPython>=7.34.0->compiam) (0.8.6)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.51.0->librosa>=0.10.1->compiam) (0.43.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl>=3.0.10->mirdata==0.3.9->compiam) (2.0.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->mirdata==0.3.9->compiam) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->mirdata==0.3.9->compiam) (2025.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->IPython>=7.34.0->compiam) (0.7.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.1->librosa>=0.10.1->compiam) (4.9.2)
Collecting mido>=1.1.16 (from pretty-midi>=0.2.10->mirdata==0.3.9->compiam)
  Downloading mido-1.3.3-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: importlib_resources in /usr/local/lib/python3.12/dist-packages (from pretty-midi>=0.2.10->mirdata==0.3.9->compiam) (6.5.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython>=7.34.0->compiam) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->compmusic==0.4->compiam) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->compmusic==0.4->compiam) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->compmusic==0.4->compiam) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->compmusic==0.4->compiam) (2026.1.4)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (6.5.7)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.0.1->jams>=0.3.4->mirdata==0.3.9->compiam) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.0.1->jams>=0.3.4->mirdata==0.3.9->compiam) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.0.1->jams>=0.3.4->mirdata==0.3.9->compiam) (0.30.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->compiam) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->compiam) (5.9.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (25.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (7.17.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (0.24.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (1.3.3)
Collecting boto3>=1.9.17 (from smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam)
  Downloading boto3-1.42.59-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: google-cloud-storage>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam) (3.9.0)
Collecting azure-storage-blob (from smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam)
  Downloading azure_storage_blob-12.28.0-py3-none-any.whl.metadata (26 kB)
Collecting azure-common (from smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam)
  Downloading azure_common-1.1.28-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting azure-core (from smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam)
  Downloading azure_core-1.38.2-py3-none-any.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.1/48.1 kB 3.5 MB/s eta 0:00:00
Collecting paramiko (from smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam)
  Downloading paramiko-4.0.0-py3-none-any.whl.metadata (3.9 kB)
Collecting backports.zstd>=1.0.0 (from smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam)
  Downloading backports_zstd-1.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting botocore<1.43.0,>=1.42.59 (from boto3>=1.9.17->smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam)
  Downloading botocore-1.42.59-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3>=1.9.17->smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3>=1.9.17->smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: google-auth<3.0.0,>=2.26.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage>=2.6.0->smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam) (2.47.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.27.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage>=2.6.0->smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam) (2.30.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage>=2.6.0->smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage>=2.6.0->smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam) (2.8.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage>=2.6.0->smart-open>=5.0.0->smart-open[all]>=5.0.0->mirdata==0.3.9->compiam) (1.8.0)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (2.21.2)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets<8,>=7.0.0->compiam) (25.1.0)

In [1]:
from compiam import load_corpora
import compiam
import os
import pandas as pd

In [2]:
carnatic = load_corpora("carnatic", token="e6c8a77bc7da6580c3220c220ccc0e0cf7948244")

WARNING:compiam.dunya:
            Note that a part of the collection is under restricted access.
            To access the full collection please request permission at https://dunya.compmusic.upf.edu/user/profile/

In [3]:
raga_ds= compiam.load_dataset("compmusic_raga")
raga_ds

800kB [00:00, 893kB/s]

The compmusic_raga dataset
----------------------------------------------------------------------------------------------------


Call the .cite method for bibtex citations.
----------------------------------------------------------------------------------------------------


CompMusic Raga Dataset class

    Args:
        track_id (str): track id of the track
        data_home (str): Local path where the dataset is stored. default=None
            If `None`, looks for the data in the default directory, `~/mir_datasets`

    Attributes:
        audio_path (str): path to audio file
        tonic_path (str): path to tonic annotation
        tonic_fine_tuned_path (str): path to tonic fine-tuned annotation
        pitch_path (str): path to pitch annotation
        pitch_post_processed_path (str): path to processed pitch annotation
        nyas_segments_path (str): path to nyas segments annotation
        tani_segments_path (str): path to tani segments annotation

    Cached Properties:
        tonic (float): tonic annotation
        tonic_fine_tuned (float): tonic fine-tuned annotation
        pitch (F0Data): pitch annotation
        pitch_post_processed (F0Data): processed pitch annotation
        nyas_segments (EventData): nyas segments annotation
        tani_segments (EventData): tani segments annotation
        recording (str): name of the recording
        concert (str): name of the concert
        artist (str): name of the artist
        mbid (str): mbid of the recording
        raga (str): raga in the recording
        ragaid (str): id of the raga in the recording
        tradition (str): tradition name (carnatic or hindustani)
    ----------------------------------------------------------------------------------------------------

In [4]:
raga_ds.download()

3.36GB [02:07, 28.4MB/s]

In [5]:
# dir(raga_ds)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_download_info',
 '_get_partitions',
 '_index',
 '_index_data',
 '_license_info',
 '_metadata',
 '_multitrack',
 '_multitrack_class',
 '_track',
 '_track_class',
 'bibtex',
 'choice_multitrack',
 'choice_track',
 'cite',
 'data_home',
 'default_path',
 'download',
 'get_metadata',
 'get_mtrack_splits',
 'get_random_mtrack_splits',
 'get_random_track_splits',
 'get_track_splits',
 'index_path',
 'license',
 'load_multitracks',
 'load_tracks',
 'mtrack_ids',
 'multitrack',
 'name',
 'readme',
 'remotes',
 'track',
 'track_ids',
 'validate',
 'version']

In [6]:
# track_ids = raga_ds.track_ids
# print(len(track_ids))

477

In [7]:
# #inspect any one track to get features
# t= raga_ds.track(track_ids[0])
# dir(t)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_data_home',
 '_dataset_name',
 '_metadata',
 '_track_metadata',
 '_track_paths',
 'artist',
 'audio',
 'audio_path',
 'concert',
 'get_path',
 'mbid',
 'nyas_segments',
 'nyas_segments_path',
 'pitch',
 'pitch_path',
 'pitch_post_processed',
 'pitch_post_processed_path',
 'raga',
 'ragaid',
 'recording',
 'tani_segments',
 'tani_segments_path',
 'to_jams',
 'tonic',
 'tonic_fine_tuned',
 'tonic_fine_tuned_path',
 'tonic_path',
 'track_id',
 'tradition']

In [8]:
# tid = raga_ds.track_ids[0]
# t = raga_ds.track(tid)

# print("Track ID:", t.track_id)

Track ID: K__V__Narayanaswami.Ethuku_Ithanai

In [9]:
import pandas as pd

rows = []

for tid in raga_ds.track_ids:
    t = raga_ds.track(tid)

    rows.append({
        "track_id": t.track_id,
        "artist": t.artist,
        "raga": t.raga,
        "tradition": t.tradition,
        "audio_path": t.audio_path
    })

df = pd.DataFrame(rows)

df.head()

,track_id,artist,raga,tradition,audio_path
0,K__V__Narayanaswami.Ethuku_Ithanai,K__V__Narayanaswami,Suraṭi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
1,Prasanna_Venkataraman.Angarakam,Prasanna_Venkataraman,Suraṭi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
2,T__M__Krishna.Aiyan_Azhagan_-_Azhagarkoil,T__M__Krishna,Suraṭi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
3,Sanjay_Subrahmanyan.Angaraka_Ashrayamyaham,Sanjay_Subrahmanyan,Suraṭi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
4,Sanjay_Subrahmanyan.Adiyapadattai,Sanjay_Subrahmanyan,Suraṭi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...

In [10]:
df["raga"].value_counts()

raga
Suraṭi              12
Śrīranjani          12
Karaharapriya       12
Mōhanaṁ             12
Sencuruṭṭi          12
Bhairavi            12
Varāḷi              12
Pūrvīkaḷyāṇi        12
Sāvēri              12
Bilahari            12
Kalyāṇi             12
Sahānā              12
Nāṭa                12
Dēvagāndhāri        12
Kānaḍa              12
Tōḍi                12
Dhanyāsi            12
Ṣanmukhapriya       12
Rītigauḷa           12
Sindhubhairavi      12
Kāṁbhōji            12
Madhyamāvati        12
Kāmavardani         12
Śrī                 12
Māyāmāḷavagauḷa     12
Ānandabhairavi      12
Aṭāna               12
Behāg               12
Gauḷa               12
Śankarābharaṇaṁ     12
Mukhāri             12
Kēdāragauḷa         12
Yadukula kāṁbōji    12
Nāṭakurinji         12
Kamās               12
Harikāmbhōji        12
Kāpi                12
Hussēnī             11
Bēgaḍa              11
Sāma                11
Name: count, dtype: int64

In [11]:
selected_ragas = [
    "Tōḍi",
    "Kalyāṇi",
    "Śankarābharaṇaṁ",
    "Karaharapriya",
    "Harikāmbhōji",
    "Māyāmāḷavagauḷa",
    "Kāmavardani",
    "Bhairavi",
    "Ānandabhairavi",
    "Sahānā",
    "Bēgaḍa",
    "Kāṁbhōji",
    "Rītigauḷa",
    "Mōhanaṁ",
    "Hamsadhwani",
    "Hindōḷaṁ",
    "Madhyamāvati",
    "Nāṭakurinji",
    "Kāpi",
    "Dhanyāsi"
]

In [12]:
df_20= df[df["raga"].isin(selected_ragas)]
df_20

,track_id,artist,raga,tradition,audio_path
12,Abhishek_Raghuram.Nidhi_Chala_Sukhama,Abhishek_Raghuram,Kalyāṇi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
13,Abhishek_Raghuram.Isha_Paahimam,Abhishek_Raghuram,Kalyāṇi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
14,Sanjay_Subrahmanyan.Vanajakshi_-_Varnam,Sanjay_Subrahmanyan,Kalyāṇi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
15,Sanjay_Subrahmanyan.Paarengum,Sanjay_Subrahmanyan,Kalyāṇi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
16,Sanjay_Subrahmanyan.Ambarame_Tannire,Sanjay_Subrahmanyan,Kalyāṇi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
...,...,...,...,...,...
472,Sikkil_Gurucharan.Meevalla_Gunadosha,Sikkil_Gurucharan,Kāpi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
473,Sikkil_Gurucharan.Kanaka_Sabhaiyai,Sikkil_Gurucharan,Kāpi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
474,Kunnakkudi_M_Balamuralikrishna.Aravinda_Pada_M...,Kunnakkudi_M_Balamuralikrishna,Kāpi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
475,O__S__Thyagarajan.Jagadodharana,O__S__Thyagarajan,Kāpi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...
476,Gayathri_Venkataraghavan.Jagadodharana,Gayathri_Venkataraghavan,Kāpi,carnatic,/root/mir_datasets/compmusic_raga/RagaDataset/...

In [14]:
LOCAL_AUDIO_ROOT = "C:/Users/Sragv/MIR Carnatic raga identification/data/raw_audio/Indian Art Music Raga Recognition Dataset (audio)"

In [15]:
def rewrite_path(original_path):
    # Find where RagaDataset begins
    idx = original_path.find("RagaDataset")

    if idx == -1:
        raise ValueError(f"'RagaDataset' not found in path: {original_path}")

    relative_part = original_path[idx:]

    # Build new absolute path
    return f"{LOCAL_AUDIO_ROOT}/{relative_part}"

In [16]:
df_20["audio_path"] = df_20["audio_path"].apply(rewrite_path)

In [18]:
df_20.head()

,track_id,artist,raga,tradition,audio_path
12,Abhishek_Raghuram.Nidhi_Chala_Sukhama,Abhishek_Raghuram,Kalyāṇi,carnatic,C:/Users/Sragv/MIR Carnatic raga identificatio...
13,Abhishek_Raghuram.Isha_Paahimam,Abhishek_Raghuram,Kalyāṇi,carnatic,C:/Users/Sragv/MIR Carnatic raga identificatio...
14,Sanjay_Subrahmanyan.Vanajakshi_-_Varnam,Sanjay_Subrahmanyan,Kalyāṇi,carnatic,C:/Users/Sragv/MIR Carnatic raga identificatio...
15,Sanjay_Subrahmanyan.Paarengum,Sanjay_Subrahmanyan,Kalyāṇi,carnatic,C:/Users/Sragv/MIR Carnatic raga identificatio...
16,Sanjay_Subrahmanyan.Ambarame_Tannire,Sanjay_Subrahmanyan,Kalyāṇi,carnatic,C:/Users/Sragv/MIR Carnatic raga identificatio...

In [19]:
from google.colab import files
df_20.to_csv("raga_20_dataset.csv", index=False)
files.download("raga_20_dataset.csv")